services:
  - type: web
    name: foodingo-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: CLIENT_URL
        value: https://foodingo-yp5a.onrender.com
      - key: NODE_ENV
        value: production
